### PR TITLE
chore: Add an integration test for profiling

### LINKED ISSUE #532: Include async-profiler v2 into the HDFS & HBase images
This allows users to start a _profile_ run for those tools from the Web UI which makes it much easier for support staff and administrators to diagnose performance issues.

Part of this work will be [upstreamed](https://issues.apache.org/jira/browse/HBASE-28242) at HBase but only for the upcoming 3.x version.
We still need to propose the same changes to the HDFS project.

The current work can be found in the `SUP-56` branch.

Tasks left to do (might be incomplete):
- [x] Add a test which checks whether the profiler servlet is available (only 200/404 status check)
- [x] Remove hardcoded version numbers
- [x] Mirror the async-profiler binary to our own repository
- [x] Remove workarounds to make the images compatible with 23.7

### PR DESCRIPTION
**Pull request by siegfriedweber**
# Description

Add an integration test for profiling

Tests stackabletech/docker-images#540

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [x] Changes are OpenShift compatible
- [x] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

### CODE REVIEW

**Comment by siegfriedweber** [comment]
Tests have succeeded:

https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hdfs-operator-it-custom/117/

**Comment by siegfriedweber** [comment]
https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hdfs-operator-it-custom/122/

**Review by razvan — DISMISSED** [review]
works

**Review by razvan — APPROVED** [review]
looks good!

**Pull request merged**
