### PR TITLE
[Merged by Bors] - Consolidate top level config

### PR DESCRIPTION
**Pull request by maltesander**
# Description

Part of https://github.com/stackabletech/hdfs-operator/issues/289

## Review Checklist

- [ ] Code contains useful comments
- [ ] CRD change approved (or not applicable)
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Comment by maltesander** [comment]
test: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hdfs-operator-it-custom/54/

**Comment by fhennig** [comment]
Code _looks_ good :+1:

**Review by fhennig — APPROVED** [review]
molto bene!

**Comment by maltesander** [comment]
bors merge

**Pull request closed without merging**
