### PR TITLE
[Merged by Bors] - feat: Support podOverrides

### PR DESCRIPTION
**Pull request by sbernauer**
# Description

*Please add a description here. This will become the commit message of the merge request later.*

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [x] Changelog updated
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [x] Feature Tracker has been updated
- [x] Proper release label has been added
```

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by razvan — COMMENTED** [review]
code looks good.
some docs and a test run are missing

**Review by razvan — APPROVED** [review]

**Comment by sbernauer** [comment]
For the docs we have https://docs.stackable.tech/home/nightly/concepts/overrides.html#_pod_overrides, is that sufficient for you?

**Comment by razvan** [comment]
It's sufficient for me. I thought we want to link it from the operator docs

**Comment by sbernauer** [comment]
Happy to do so, any recommendation from where exactly we want to link? Goes along with the questions of how hard we want to try to avoid users using podOverrides ^^

**Comment by sbernauer** [comment]
Started https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hdfs-operator-it-custom/92/

**Comment by sbernauer** [comment]
bors r+
Added a test, which passed locally

**Pull request closed without merging**
