### PR TITLE
Cleanup and bring up to speed with current best practices

### PR DESCRIPTION
**Pull request by lfrancke**
- Sort dependencies
- Add license information
- Don't try to create the CRD automatically
- Move CRD to deploy/crd directory

### CODE REVIEW

**Review by lfrancke — COMMENTED** [review]
##### Automated comment from CodeApprove ([go to review](https://codeapprove.com/pr/stackabletech/hdfs-operator/44))



<hr />

In: **.github/workflows/rust.yml**:

```
> Line 75
        run: cargo clippy --all-targets -- -D warnings
```
This causes the build to break on warnings.
Seems sensible to me but means I need to fix the warnings now as well :)

**Review by soenkeliebau — COMMENTED** [review]
##### Automated comment from CodeApprove ([go to review](https://codeapprove.com/pr/stackabletech/hdfs-operator/44))



<hr />

In: **.github/workflows/build_artifacts.yml**:

```
> Line 60
        run: sed -i -e 's/^version = "\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/version = "\1-pr${{ github.event.number }}"/' server/Cargo.toml
```
Forgot to change this pr to mr :(

<hr />

In: **docs/modules/ROOT/pages/building.adoc**:

```
> Line 5
It is developed against the latest Rust release, and we currently don't support any older versions.
```
Does "release" include nightly? Not sure if this one needs nightly tbh..

<hr />

In: **operator/Cargo.toml**:

```
> Line 3
description = "Stackable Operator for Apache Hadoop HDFS - The Operator library"
```
Why "library" with a lower case first letter?

<hr />

In: **server/packaging/rpm/SPECS/stackable-hdfs-operator-server.spec**:

```
> Line 15
License: ASL 2.0
```
You changed the license to the OSL3.0


<hr />

👀 @lfrancke it's your turn please take a look

**Review by lfrancke — COMMENTED** [review]
##### Automated comment from CodeApprove ([go to review](https://codeapprove.com/pr/stackabletech/hdfs-operator/44))



<hr />

In: **.github/workflows/build_artifacts.yml**:
Fixed

<hr />

In: **server/packaging/rpm/SPECS/stackable-hdfs-operator-server.spec**:
Fixed


<hr />

👀 @soenkeliebau it's your turn please take a look

**Comment by lfrancke** [comment]
Clippy comlains about various unused things here but I think we should merge it anyway.
The HDFS operator needs a full overhaul anyway.

**Review by soenkeliebau — DISMISSED** [review]
##### Automated comment from CodeApprove ([go to review](https://codeapprove.com/pr/stackabletech/hdfs-operator/44))


✔️ Approved

<hr />

👀 @lfrancke it's your turn please take a look

**Review by soenkeliebau — APPROVED** [review]

**Pull request merged**
