### PR TITLE
fix(tests): Migrate breaking changes from #450 listener integration

### PR DESCRIPTION
**Pull request by sbernauer**
# Description

*Please add a description here. This will become the commit message of the merge request later.*

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/style-guide).
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

### CODE REVIEW

**Review by NickLarsenNZ — DISMISSED** [review]
LGTM

**Comment by sbernauer** [comment]
https://ci.stackable.tech/job/hdfs-operator-it-custom/116/

**Review by NickLarsenNZ — APPROVED** [review]
LGTM

**Comment by sbernauer** [comment]
We fixed the problem, but we are now running into actual test failures related to WebHdfs in case external-unstable is used:
`logger.go:42: 09:05:06 | smoke_hadoop-3.3.4_zookeeper-3.8.3_zookeeper-latest-3.8.3_number-of-datanodes-2_datanode-pvcs-2hdd-1ssd_listener-class-external-unstable/50-create-file | requests.exceptions.ConnectionError: HTTPConnectionPool(host='hdfs-datanode-default-0.hdfs-datanode-default.kuttl-test-exciting-sloth.svc.cluster.local', port=32626): Max retries exceeded with url: /webhdfs/v1/testdata.txt?op=CREATE&user.name=stackable&namenoderpcaddress=hdfs&createflag=&createparent=true&overwrite=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbe5b054a50>: Failed to establish a new connection: [Errno 111] Connection refused'))`

This is probably caused because the POST to the NameNode redirects to a wrong DataNode address in the tests
https://github.com/stackabletech/hdfs-operator/blob/cf39abe1763d1e3bc794c5dfbc664e73b3ab6c53/tests/templates/kuttl/smoke/webhdfs.py#L34

**Pull request merged**
