### PR TITLE
[Merged by Bors] - Emit errors as K8s events

### LINKED ISSUE #85: Write Kubernetes Events for errors during reconciliation
We would like to emit Kubernetes events for all errors, please see the epic for details https://github.com/stackabletech/issues/issues/158

### PR DESCRIPTION
**Pull request by nightkr**
## Description

Fixes #85 

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by maltesander — COMMENTED** [review]
unused dependencies:
`stackable-hdfs-operator v0.4.0-nightly (/home/runner/work/hdfs-operator/hdfs-operator/rust/operator)`
└─── dependencies
     └─── "async-trait"

you can remove the async-trait

**Comment by nightkr** [comment]
Sorted @maltesander

**Review by maltesander — APPROVED** [review]
LGTM.

**Pull request closed without merging**
