### PR TITLE
Allow dashes in port names (again)

### LINKED ISSUE #514: Port names with dashes are not supported in sidecar containers
## Port names with dashes are not supported in sidecar containers

The following example adds an OAuth proxy to the HDFS name nodes via `podOverrides`. A port is defined with a name that contains a dash.

```yaml
---
apiVersion: hdfs.stackable.tech/v1alpha1
kind: HdfsCluster
spec:
  nameNodes:
    podOverrides:
      spec:
        containers:
          - name: oauth-proxy
            image: quay.io/openshift/origin-oauth-proxy:4.12
            ports:
              - name: oauth-proxy
                containerPort: 8080
            ...
```

The namenode container uses this bash script to export the ports as environment variables:

```
if [[ -d /stackable/listener ]]; then
    export POD_ADDRESS=$(cat /stackable/listener/default-address/address)
    for i in /stackable/listener/default-address/ports/*; do
        export $(basename $i | tr a-z A-Z)_PORT="$(cat $i)"
    done
fi
```

This leads to the following error:

```
+ for i in /stackable/listener/default-address/ports/*
++ tr a-z A-Z
++ basename /stackable/listener/default-address/ports/oauth-proxy
++ cat /stackable/listener/default-address/ports/oauth-proxy
+ export OAUTH-PROXY_PORT=8080
/bin/bash: line 39: export: `OAUTH-PROXY_PORT=8080': not a valid identifier
```

The problem is that `-` is not allowed in an environment variable name.

A solution would be to convert the port name to a valid environment variable name. Attention must be paid because port names can start with a digit, e.g. `123-web`, whereas environment variables cannot.

Another solution would be to not export these ports.

### PR DESCRIPTION
**Pull request by nightkr**
# Description

Fixes #514

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [x] Changes are OpenShift compatible
- [x] Helm chart can be installed and deployed operator works
- [x] Integration tests passed (for non trivial changes)
- [x] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs-style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

### CODE REVIEW

**Review by sbernauer — APPROVED** [review]
Thanks for fixing! All other cases should be handled

> As with Kubernetes [names](https://kubernetes.io/docs/concepts/overview/working-with-objects/names) in general, names for ports must only contain lowercase alphanumeric characters and -. Port names must also start and end with an alphanumeric character.

Just for the record from https://github.com/stackabletech/hdfs-operator/issues/514#issuecomment-2090601235

> I'd argue that 123-abc is far less common, and while switching to a PORT_ prefix would fix it, I'm not sure it's worth the compatibility break.

**Comment by sbernauer** [comment]
Thinking about it, would anything else than `rust/operator-binary/src/hdfs_controller.rs` be affected by adding a `PORT_` prefix?
We set e.g. `dfs.datanode.registered.port` to `${env.DATA_PORT}`, shouldn't his be unnoticed by customers?

**Comment by nightkr** [comment]
(Merging since digit-prefixed ports are a separate fix anyway, but can continue discussing in here or make a new issue)

>  We set e.g. dfs.datanode.registered.port to ${env.DATA_PORT}, shouldn't his be unnoticed by customers?

In the default configuration, no. But they can still use `${env.}` references in their own config overrides, which _would_ be broken by it.

**Comment by nightkr** [comment]
It would definitely have been better to do it that way from the start. Now we have the tradeoff to make.

**Comment by sbernauer** [comment]
I think the likelihood of someone doing that is very very unlikely and I personally would prefer to be safe in the long run

**Comment by nightkr** [comment]
To be clear, the options here are:

- Break previously-working configurations during routine upgrades, with an unclear cause or path forward
- Break when applying a new configuration that trips over the edge case, which can easily be reverted

**Comment by sbernauer** [comment]
Honestly I don't care to much, I leave it up to you

**Pull request merged**
